### ISSUE TITLE
Please, users, this is bannable 

### ISSUE THREAD

**Issue by riahc3** [JustOscarJ1/valorant_lineup_calculator#1]
Even though this will get removed by the repo owner, I just want to note that this is bannable and hardware bannable.

This directly helps gives a completive advantage versus others players which Riot does not allow. I am just warning everyone 

I ask the repo owner to add this as a warning, that's all

**Comment by JustOscarJ1** [comment]
Hi, this is actually not bannable. According to the Riot TOS:

> The following are examples of behaviour that warrant disciplinary measures:
> 
> Using any unauthorized third party programs, including mods, hacks, cheats, scripts, bots, trainers and automation programs that interact with the Riot Services in any way, for any purpose, including any unauthorized third party programs that intercept, emulate, or redirect any communication relating to the Riot Services and any unauthorized third party programs that collect info about the Riot Services by reading areas of memory used by the Riot Services to store info;

This program does not intercept, emulate or redirect any communication to any Riot services. It does not read any memory or collect any information used by Riot services. Whilst this does give an in-game advantage, the way it is made makes it not bananble according to Riots TOS. There are other very popular applications which may not be as direct in their methods, but have the same end-goal, like Valorant Tracker.

**Comment by riahc3** [comment]
This is a unauthorized third party program. Period. Also, this is a script as it calculates where your mouse is pointing. It's like saying a macro is allowed when it isn't.

I urge users NOT to use this: If a ban wave comes, @JustOscarJ1 will NOT be able to get your account unbanned and since it is a hardware ban, you will not be able to make another account. I am trying to help the community by giving a fair warning.

**Comment by JustOscarJ1** [comment]
No, it's not that straightforward. Theoretically, you could label any program on your computer as an "unauthorized third-party program," but Riot Games has clearly outlined guidelines for blacklisted third-party programs. It's important to emphasize that my program does not interfere with any Riot services or interact with the game in any manner. It simply performs calculations.

I never stated that macros are allowed because, in fact, they violate the TOS by emulating communication with Riot services through self-generated input. Comparing macros to my program is a significant leap. Furthermore, if there were any changes to the TOS in the future (which is highly unlikely), I would promptly include a warning in the readme.

Lastly, since the program does not interact with Riot services in any way, the likelihood of an automatic ban by Vanguard is extremely low. The only scenario in which users of this program might face a ban is if Riot manually investigates and targets this specific program.

I kindly request that you refrain from attempting to alarm users unless you possess clear evidence demonstrating a violation of the TOS.

**Comment by riahc3** [comment]
Have you been authorized by Riot to create and distribute this program?

If the answer is no, then this is a unauthorized third-party program and breaks TOS.

Biltz, Tracker, etc. are all authorized by Riot and have been in contact with them.

I have already submitted a ticket to Riot about your program and they have confirmed that this program is not authorized, breaking TOS. 

Again users: Use this under your own responsibility. Open a Riot support ticket instead of reading the dev.

**Comment by JustOscarJ1** [comment]
It appears you are completely ignoring my completely objective and sound argument and still remaining steadfast in your view any unauthorised third party app which provides an advantage is against TOS.

Please show me exactly where it says this, and please tell me why the piece of text I got directly from the TOS is not correct. 

You cannot simply say something is against TOS with no proof while I give direct sources.

Lastly, if you have specific confirmation from Riot that this program is against TOS, why not provide the logs to back this up? That would be absolutely critical information that could end this discussion.

**Comment by riahc3** [comment]
You completely ignored my question. Is this program (or script) a authorized third-party program by Riot? Riot makes it VERY clear that ANY unauthorized third-party program is not allowed. What you quote are "including" which are examples. Maybe thats your next defense "Riot says program, this is a script, no TOS breaking here!"

Are you the type of person that requires warning labels on everything with everything detailed and if something happens that isnt written, lawsuit? I dont understand how you can be so blind to Riot not allowing any unauthorised third party, you recognizing your program gives a advantage and STILL have the nerve to defend yourself....

**Comment by JustOscarJ1** [comment]
Hi,

No, my program has not specifically been cleared by Riot. Hope that answers your question, now I request you answer mine.

1. Where in the Riot TOS does it say any unauthorised third party program/script, or however you label it is not allowed. If this is "VERY clear" this should not be an issue.

2. If you did get specific information from Riot support that my program is not allowed, why not share it even now? Was that just a lie?

3. Why are you resorting to attacking my character? I am being strictly professional and arguing my case, I don't understand whats offensive about that.

Until you can answer these questions, no warnings will be posted.

Edit: Yes, the quote I provided does say "including",  that is for the type of program. I have never argued the labeling of my program, you making that argument for me is really disingenuous.

The important part of that quote is where it outlines what the program/script isn't allowed to do, which is basically anything with Riot services. As mentioned before, mine does not.

**Comment by riahc3** [comment]
![image](https://github.com/user-attachments/assets/7927893d-ed24-488a-94c2-c58dac07d8c6)

Here is another app that gave a clear competitive advantage, just like yours... but hey, keep believing yours doesnt (and censoring posts)

**Comment by JustOscarJ1** [comment]
That app intercepts Riot services to find when the spike is planted. It is different. Move on.
