### ISSUE TITLE
Compiled exe

### ISSUE THREAD

**Issue by AdamWHY2K** [JustOscarJ1/valorant_lineup_calculator#2]
You should create a release with a compiled exe using [pyinstaller](https://pypi.org/project/pyinstaller), that way the less technologically inclined users don't have to deal with installing python/pip/requirements. I did the same thing and you'll get way less "bug" reports

**Comment by JustOscarJ1** [comment]
made a .exe, see https://github.com/JustOscarJ1/valorant_lineup_calculator/releases/tag/Release

thanks for the feedback
