### ISSUE TITLE
Multiple monitors of different sizes break the coordinate system

### ISSUE THREAD

**Issue by YoJames2019** [JustOscarJ1/valorant_lineup_calculator#4]
~~my main monitor is 1920x1080, however I have a monitor in vertical mode which causes the coordinate max to be the height of that vertical monitor which breaks the functionality of this~~

Wait nevermind pyautogui returns the correct x and y coords so I'm not sure whats going on but this is what the program displays

**Comment by YoJames2019** [comment]
![image](https://github.com/JustOscarJ1/valorant_lineup_calculator/assets/49845975/89926988-f9e4-4f1a-a08e-9b2ace30dd6c)

**Comment by YoJames2019** [comment]
I assumed it was some kind of weird display coords bug because of this and the fact that sometimes the y coordinate wont go past a specific number but it isnt consistent, (for example one time it thought the bottom of the screen was -251 and the top of the screen was -1330)

**Comment by JustOscarJ1** [comment]
make sure you're using the program correctly... follow the steps and when moving to the top of your screen keep your mouse inline with the ping
