### ISSUE TITLE
Add a scrollbar or minimize a settings set GUI.

### ISSUE THREAD

**Issue by acerkasov** [JustOscarJ1/valorant_lineup_calculator#5]
![forissue](https://github.com/JustOscarJ1/valorant_lineup_calculator/assets/61025964/15639ca0-92a9-4da9-b37d-f5d7c3003449)
That's how it looks like on a 1336x768 monitor, I found it out only bc I wasn't using a main pc.
I tried to add a scrollbar rewriting settings GUI but... I didn't success.

**Comment by JustOscarJ1** [comment]
I did an overhaul of the settings menu on the latest release, does the issue persist?

**Comment by acerkasov** [comment]
![forissue2](https://github.com/JustOscarJ1/valorant_lineup_calculator/assets/61025964/0526459a-e0c1-4b9d-a0e8-f24d3034082d)
Looks way more beautiful but issue still persists

**Comment by acerkasov** [comment]
There are [examples](https://github.com/TomSchimansky/CustomTkinter/blob/master/examples/scrollable_frame_example.py) of CustomTkinter scrollable frames, but not scrollable windows, and they also use grid geometry manager.
Hope this helps :3

**Comment by JustOscarJ1** [comment]
https://gyazo.com/3782dcbee12b446c78897022fc190592

Is this what you're looking for?

**Comment by acerkasov** [comment]
Yes, 😍
